### PR TITLE
DOJ-541: Add human-readable output for webform email submissions.

### PR DESCRIPTION
**Pull request by brockfanning**

### CODE REVIEW

**Comment by brockfanning** [comment]
@malikkotob Matt gave the go-ahead for this here: https://github.com/usdoj/foia.gov/issues/541
Any objection to merging this?

**Comment by malikkotob** [comment]
@brockfanning the code looks good, but I haven't had a chance to run automated tests. Have you run `blt tests` locally to make sure there are no regressions?

**Comment by brockfanning** [comment]
@malikkotob I just ran `blt tests` locally, and got no failures.

**Comment by malikkotob** [comment]
@brockfanning okay great. I don't see any reason not to go ahead and merge this then!

**Pull request merged**
