### PR TITLE
Sk jiraticket inc1345922

### PR DESCRIPTION
**Pull request by sundarcreosen**

### CODE REVIEW

**Comment by sundarcreosen** [comment]
@brockfanning Updated the permission.

**Comment by brockfanning** [comment]
@sundarcreosen This PR has some unrelated file changes (the "Delete after 7 days") stuff.

**Comment by brockfanning** [comment]
@sundarcreosen I think you just need to merge the latest code from "develop" into your branch and then push it again.

**Comment by sundarcreosen** [comment]
@brockfanning  (the "Delete after 7 days") for this ticket do i need to work again and push it
Only these two files i pushed docroot/modules/custom/foia_request/src/Entity/FoiaRequest.php ,  config/default/views.view.foia_requests.yml

**Pull request closed without merging**
